=== lunalovecraft14/4-2-South-Racing/teams.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://www.example.com/teams"
           targetNamespace="http://www.example.com/teams"
           elementFormDefault="qualified">

    <!-- Define the teams element -->
    <xs:element name="teams">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="team" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="description" type="xs:string"/>
                            <xs:element name="series" type="xs:string"/>
                            <xs:element name="cars">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="car" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="title" type="xs:string"/>
                                                    <xs:element name="model" type="xs:string"/>
                                                    <xs:element name="driver" type="xs:string"/>
                                                </xs:sequence>
                                                <xs:attribute name="cid" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="tid" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== lunalovecraft14/4-2-South-Racing/teamcars.xml
<!--
   New Perspectives on XML
   Tutorial 4
   Case Problem 4

   South Racing teams list
   Author: Melissa Coates
   Date: July 24, 2024

   Filename:         teamscars.xml
   Supporting Files: teams.css, cars.css, cars.xml, teams.xsd, cars.xsd
-->

<?xml-stylesheet type="text/css" href="teams.css"?>
<?xml-stylesheet type="text/css" href="cars.css"?>

<teams xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://example.com/teams"
       xsi:schemaLocation="http://example.com/teams teams.xsd">

   <team tid="t205">
      <title>Rodas Motorsports</title>
      <description>#1 Team in racing</description>
      <series>Indy</series>
      <cars>
         <car cid="nes201">
            <title class="car-title">Straight Away</title>
            <model>Nissan</model>
            <driver>indy</driver>
         </car>
         <car cid="gda100-5">
            <title class="car-title">Quick Start</title>
            <model>General Motors</model>
            <driver>indy</driver>
         </car>
         <car cid="gma005-2">
            <title class="car-title">Stop Blocks Laps</title>
            <model>Ford</model>
            <driver>indy</driver>
         </car>
         <car cid="sob-450V4">
            <title class="car-title">Bendwinder</title>
            <model>Ford</model>
            <driver>412</driver>
         </car>
         <car cid="hen01-53">
            <title class="car-title">Turn Twister</title>
            <model>Nissan</model>
            <driver>indy</driver>
         </car>
      </cars>
   </team>

   <team tid="t105">
      <title>SAM Racing</title>
      <description>Top 10 over last 5 years</description>
      <series>Nascar</series>
      <cars>
         <car cid="nes201">
            <title class="car-title">Straight Away</title>
            <model>Nissan</model>
            <driver>indy</driver>
         </car>
         <car cid="gda100-5">
            <title class="car-title">Quick Start</title>
            <model>General Motors</model>
            <driver>indy</driver>
         </car>
         <car cid="gma005-2">
            <title class="car-title">Stop Blocks Laps</title>
            <model>Ford</model>
            <driver>indy</driver>
         </car>
         <car cid="stu-050V4">
            <title class="car-title">Sleeker</title>
            <model>General Motors</model>
            <driver>278</driver>
         </car>
         <car cid="dej01-003">
            <title class="car-title">84 Racer</title>
            <model>General Motors</model>
            <driver>198</driver>
         </car>
      </cars>
   </team>

</teams>
